#' @title CCC_model testing for the evaluation of the standards dataset
#' @description A wrapper function to test a specific model on the X-Y dataset generated by the dataset.building function
#' @param X1Y the dataset given by the dataset.building function 
#' @param ntest the number of test to repeat on the dataset 
#' @param variables chose eiher between the "categorical" or "ordinal" variables. Categorical variables include: Sulfur, Phosphate, acidic, Nitrogen, Heterocycles, C/O ratio and Glycosides. The ordinal variables include the phenols and aliphatic moiety.
#' @param model the statistical model to apply: choose between "pls", "lasso", "ridge", "logistic"  
#' @param errors the kind of error you want to test on the dataset. Choose between "ppm", (mass accuracy error) "Cees" (Carbon estimation error), and "nerr" (normal distributed error) 
#' @usage test.model(X1Y, model, variables, ntest, errors)
#' @author Luca Narduzzi "nardluca@gmail.com"
#' @return a list containing the values of the accuracy of the model across the error values. The accuracy is given with 3 parameters: the means_All (percentage of correct predictions) sds_All (percentage of standard deviation) and the MSEE (root mean squared error). It returns also a plot of the test, indicating the accuracy mean across the measurement error.
#' @export "test.model"
#' @examples 
#' STD_RP <- read.csv(system.file("extdata", "STD_RP.csv", package = "CCC"), row.names = 1, stringsAsFactors = FALSE)
#' X1Y <- dataset.building(STD_RP)
#' results <- test.model(X1Y, model = "lasso", variables = "categorical", ntest = 100, errors = "ppm")

test.model <- function(X1Y, model, variables, ntest = 100, errors) {
  if (variables != "categorical" & variables != "ordinal") {stop("please indicate the type of variables to test between categorical and ordinal")}
  if (variables == "categorical" & (errors == "none" | errors == "nerr")) {
    nyc = c(1,2,4,5,6,8,9)
    results <- model.test(X1Y, model = model, ntest = ntest, nyc = nyc, errors = errors)
  } 
  if (variables == "categorical" & (errors == "ppm" | errors == "Cees")) {
    nyc = c(1,2,4,5,6,8,9)
    results <- model.testing(X1Y, model = model, ntest = ntest, nyc = nyc, errors = errors)
  } 
  if (variables == "ordinal") {
    if (errors == "logistic") {stop("logistic model cannot be applied on ordinal variables")}
    nyc = c(3,7)
results <- model.testing(X1Y, ntest = ntest, nyc = nyc, errors = errors, model = model)
    }
  return(results)
}

  
  